spring:
  application:
    name: ApiGateway

  profiles:
    active: local

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/api/v1/auth/**

        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/v1/users/**,/api/v1/cards/**

        - id: order-service
          uri: http://order-service:8082
          predicates:
            - Path=/api/v1/orders/**,/api/v1/items/**

        - id: payment-service
          uri: http://payment-service:8083
          predicates:
            - Path=/api/v1/payments/**

server:
  port: 8079